[package]
name = "timelapst"
version = "0.1.0"
authors = ["Leon Si <leonzalion@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { git = "https://github.com/hecrj/iced", features = [ "glow" ] }
